apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: australiajobseeker
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
  - name: ollama
    port: 11434
    targetPort: 11434
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-external
  namespace: australiajobseeker
spec:
  type: LoadBalancer
  selector:
    app: ollama
  ports:
  - name: ollama
    port: 11434
    targetPort: 11434
    protocol: TCP
